version: '3'

services:
  web:
    build:
      context: .
    container_name: flask-ebook
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: >
      sh -c "flask run --host=0.0.0.0 --port=5000"
    environment:
      FLASK_APP: app.py  # Replace `app.py` with your main Flask application file
      FLASK_ENV: development